### ISSUE TITLE
Error when getting a message that has only attributes

### ISSUE THREAD

**Issue by macabeus** [nubolab-ffwd/svelte-fluent#695]
We may need a message with only attributes, then our Svelte code will be something like:

```svelte
<Localized id="foo" let:attrs>
 <p>{attrs.paragraph1}</p>
</Localized>
```

But it crashes when loading a message like this one:

```fluent
foo =
  .bar = example
```

while it works in this case:

```fluent
foo = fix
  .bar = example
```

Error log:
```
TypeError: Invalid value used in weak set
    at WeakSet.add (<anonymous>)
    at resolveComplexPattern (resolver.js:232:17)
    at FluentBundle.formatPattern (bundle.js:150:25)
    at FluentProvider.svelte:27:25
    at $$self.$$.update (Localized.svelte:7:19)
    at init (index.mjs:2027:8)
    at new Localized (Localized.svelte:7:43)
    at Array.create_default_slot (RowWhatIsGambiConf.svelte:37:28)
    at create_slot (index.mjs:71:28)
    at create_fragment (Window.svelte:46:23)
```

**Comment by sfriedel** [comment]
@macabeus thanks for reporting. This should be fixed in the next release.
